// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjxAkK_zC0r3L2B3gtsfn2lc9WYOmF4rE',
    appId: '1:577240695048:web:c156ef798a4ac07a4dacbd',
    messagingSenderId: '577240695048',
    projectId: 'mboawaste',
    authDomain: 'mboawaste.firebaseapp.com',
    storageBucket: 'mboawaste.appspot.com',
    measurementId: 'G-R76Z7MT3KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3uc-PqYytWpcLBYV-93uBhlTzSVZZOks',
    appId: '1:577240695048:android:4bb7b919f14006074dacbd',
    messagingSenderId: '577240695048',
    projectId: 'mboawaste',
    storageBucket: 'mboawaste.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCxQszlpQe0rVQJ2LtbnDfP9lT1iYrCJI',
    appId: '1:577240695048:ios:e6d960de09f21b764dacbd',
    messagingSenderId: '577240695048',
    projectId: 'mboawaste',
    storageBucket: 'mboawaste.appspot.com',
    iosClientId: '577240695048-iuqnt1vrv784obfpnmc9emuoiv4bfr3l.apps.googleusercontent.com',
    iosBundleId: 'intellisoft.mboawaste.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCxQszlpQe0rVQJ2LtbnDfP9lT1iYrCJI',
    appId: '1:577240695048:ios:e6d960de09f21b764dacbd',
    messagingSenderId: '577240695048',
    projectId: 'mboawaste',
    storageBucket: 'mboawaste.appspot.com',
    iosClientId: '577240695048-iuqnt1vrv784obfpnmc9emuoiv4bfr3l.apps.googleusercontent.com',
    iosBundleId: 'intellisoft.mboawaste.app',
  );
}
